version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
  web:
    build: .
    command: python unitystation_auth/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/djangoapp
    ports:
      - "8000:8000"
    depends_on:
      - db

