version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  test:
    image: unitystation/central-command
    env_file: ./example.env
    command: test
